host: 0.0.0.0

sass:
  style: compressed

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "ziris | kunst en fotografie"
      description: "Ziris biedt cursussen aan op het gebied van kunstgeschiedenis in combinatie met fotografie en beoogt een verbinding te maken tussen kunsttheorie en praktijk."
      img: /assets/img/ziris-og-image.png
      header-animation: a-del-150
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /cursussen/:title
      header: header--white