host: 0.0.0.0

sass:
    style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "ziris | kunst en fotografie"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /cursussen/:title
      header: header--white