host: 0.0.0.0

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "ziris | kunst en fotografie"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /cursussen/:title
      header: header--white