backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"
publish_mode: editorial_workflow

collections:
  - label: "Pagina's"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        widget: "object"
        fields:
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields: 
              - {label: "Titel", name: "title", widget: "string", default: "maak de klik tussen kunst en fotografie"}
              - {label: "Subtitel", name: "subtitle", widget: "text", required: false}
              - {label: "Afbeelding", name: "img", widget: "image"}
              - {label: "Afb. beschrijving", name: "caption", widget: "string"}
              - {label: "Scroll indicatie", name: "discover", widget: "string", default: "ontdek meer"}
          - label: "Vervolgsectie"
            name: "art"
            widget: "object"
            fields: 
              - {label: "Titel", name: "title", widget: "string", default: "aangeleerde kijkpatronen herkennen en doorbreken"}
              - {label: "Subtitel", name: "subtitle", widget: "text", default: "helpt je om op een meer creatieve en bewuste manier te fotograferen.", required: false}
              - {label: "Afbeelding", name: "img", widget: "image"}
              - {label: "Afb. beschrijving", name: "caption", widget: "string"}
          - label: "Oproep tot actie"
            name: "pattern"
            widget: "object"
            fields: 
              - {label: "Titel", name: "title", widget: "string", default: "goede foto’s maken. zelfs met je mobiel"}
              - {label: "Subtitel", name: "subtitle", widget: "text", default: "door bij mij een cursus te volgen leer je waarom.", required: false}
              - {label: "Knop", name: "button", widget: "string"}
          - label: "Sociaal bewijs"
            name: "proof"
            widget: "object"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - label: "Cursisten"
                name: "members"
                widget: "list"
                fields: 
                  - {label: "Naam", name: "name", widget: "string"}
                  - {label: "Afbeelding", name: "img", widget: "image"}
                  - {label: "Beroep", name: "profession", widget: "string"}
                  - {label: "Citaat (niet tussen haakjes zetten)", name: "quote", widget: "text"}
      - name: "over-ziris"
        label: "Over Ziris"
        file: "over-ziris.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Header", name: "header", widget: "hidden", default: "header--white"}
          - {label: "Titel", name: "title", widget: "string", default: "over ziris kunst en fotografie"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "contact"
        label: "Contact"
        file: "_data/contact.yml"
        fields:
          - {label: "Bedrijfsnaam", name: "company", widget: "string"}
          - {label: "Locatie", name: "location", widget: "string"}
          - {label: "E-mailadres", name: "email", widget: "string"}
          - {label: "Telefoonnummer", name: "phone", widget: "string"}
      - name: "convince"
        label: "Overtuiging"
        file: "_data/convince.yml"
        fields:
          - {label: "Tekstje", name: "text", widget: "string"}

  - name: "cursussen" # Used in routes, e.g., /admin/collections/blog
    label: "Cursussen" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Categorie", name: "category", widget: "select", options: ["volwassenen", "jongeren", "kinderen"]}
      - {label: "Type les", name: "type", widget: "string", required: false}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Thumbnail", name: "thumb", widget: "image"}
      - {label: "Afbeelding", name: "img", widget: "image"}
      - {label: "Afb. beschrijving", name: "caption", widget: "string"}
      - {label: "Aantal lessen", name: "amount", widget: "string"}
      - {label: "Tijdstip", name: "time", widget: "string"}
      - {label: "Start cursus", name: "start", widget: "string"}
      - {label: "Locatie", name: "location", widget: "string"}
      - {label: "Prijs", name: "price", widget: "string"}
      - {label: "Inclusief", name: "inc", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}